### ISSUE TITLE
Installation: Could not locate "Alfred.alfredpreferences" at 

### ISSUE THREAD

**Issue by renebaeu** [steyep/alfred-jira#102]
I was not able to install alfred-jira: 

while installation, it asks:
Enter the path to your "Alfred.alfredpreferences" file:

With this error message: 
Could not locate "Alfred.alfredpreferences" at "/Users/renebaumer/Library/Application Support/Alfred 3/Alfred.alfredpreferences"

The location of the file is correct. Is there anything I can do?

node: v9.4.0
Alfred: 3.8.1 (without Powerpack)

**Comment by steyep** [comment]
It's not possible to install the workflow if you don't have a Powerpack license.

**Comment by lacco** [comment]
I was running into the same issue, even with a Powerpack license... 

It turned out that `install.sh` requires that at least one workflow was created before, otherwise the `workflow` directory isn't created yet. After creating an example workflow, I was able to install the jira workflow!

**Comment by steyep** [comment]
Nice catch, @lacco. I did not realize that. I thought Alfred came with an example workflow but perhaps that's stored elsewhere? Anyway thanks for picking my lowly little workflow to be your first 😄
