### ISSUE TITLE
Alfred 4 installation failed

### ISSUE THREAD

**Issue by khamza85** [steyep/alfred-jira#107]
I'm not sure if it is possible to install it on Alfred 4. So far I'm having no success.

**Comment by steyep** [comment]
At what point does the installation fail? It may be that you need to specify the path to your Alfred 4 workflows:

```
npm run build "$HOME/Library/Application Support/Alfred 4"
```
_I'm just guessing on the path - I do not have Alfred 4_.

If that doesn't work, can you please provide more information about the behavior you're experiencing?

**Comment by khamza85** [comment]
Your idea with explicit path worked. Thanks for a quick help

**Comment by shane-walker** [comment]
Just in case anyone else runs into this, here was the path I had to use for the build to work.
```
npm run build "$HOME/Library/Application Support/Alfred"
```
