### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by damianpoole** [steyep/alfred-jira#11]
Whenever I  attempt to log in to my companies Jira instance I get the following.

`[2016-09-27 13:48:02][input.scriptfilter] Processing output of 'action.script' with arg 'login'
[2016-09-27 13:48:30][ERROR: action.script] (node:48618) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'status' of undefined
Credentials erased!`

I couldn't get the login option to appear on node 4.5 so I am currently using 6.6.

**Comment by damianpoole** [comment]
OK so this is the issue - http://stackoverflow.com/questions/20082893/unable-to-verify-leaf-signature

**Comment by steyep** [comment]
Oh, good find! I will push out a fix for this.

**Comment by steyep** [comment]
@damianpoole, give this a shot: in the settings menu of the workflow ( `jira ► settings ►`), clear the cache and then update the workflow to pull the fix. Hopefully that will resolve your issue.
