### ISSUE TITLE
How to login on standalone JIRA server (not cloud)?

### ISSUE THREAD

**Issue by hsleedevelop** [steyep/alfred-jira#110]
How to login on standalone JIRA server (not cloud)?
I can't find about this in issue threads.

**Comment by steyep** [comment]
This workflow was designed for standalone Jira instances. The method for logging in is the same. Enter the path to your standalone server as the Jira URL on the login screen along with the credentials associated with your account on that server.

What steps did you take that led you to believe the processes might differ? If you enable debugging on the workflow (https://github.com/steyep/alfred-jira/issues/38#issuecomment-285418736), do you see any errors when trying to log in?
