### ISSUE TITLE
Ability to view issue in browser

### ISSUE THREAD

**Issue by bekinin** [steyep/alfred-jira#28]
Like with quick command jira project-123  show the search results and add action to open it in default browser

**Comment by steyep** [comment]
Perhaps I'm misunderstanding your request, but you can currently search for an issue by name:
`jira project-123` is an alias for `jira ► search ►  project-123` and will automatically convert when you press return. 

You can also open an issue in your default web browser by pressing return on the issue's summary. 

Here's an example:
![demo](https://cloud.githubusercontent.com/assets/4822034/20433986/e6bf8afc-ad73-11e6-835a-9638608e90ef.gif)

And, like I said, it's possible that I totally misunderstand the request so please let me know if that's the case. Thanks for the feedback!

**Comment by bekinin** [comment]
Yes, you answered correctly. 
My trouble that I need to wait and hit enter like 3-4 time to get it opened.

So, proposal to add quick command similar to search, which just open jira id by 1 enter
like jira open abc-123 <enter> - open it in browser

**Comment by steyep** [comment]
@bekinin, in `v.1.0.3` I've implemented this functionality. Once the workflow has been updated, you can quickly open issues in the browser like: `jiraopen abc-123`.
