### ISSUE TITLE
View my issues for current sprint

### ISSUE THREAD

**Issue by itainoam** [steyep/alfred-jira#30]
Love your plugin!

I miss the ability to view issues assigned to me in current sprint. Would you find it useful?
Any tips about how I should go about implementing it?

Cheers,
Itai

**Comment by steyep** [comment]
Thanks – I appreciate the feedback!

I actually have a generic issue open that relates to this request ( integrating with Agile boards #2  ) because I agree that it would definitely be useful. I'm currently in the process of nailing down a proper 1.0 version to release, so Agile will likely be a v2.0 feature. That said, feel free to create a pull request if you get around to integrating it sooner.

**Comment by itainoam** [comment]
Awesome. I am willing to give it try. 
While I have developed in JS quite a bit, didn't get a chance to work with Alfred. 
Where would you start? Which project files should I start digging in to?

**Comment by steyep** [comment]
Hey, @itainoam, I just pushed out an update for the workflow that may help resolve this issue for you. The update allows for the user to define the JQL query that populates the initial menu that appears when you type `jira` into Alfred (the workflow refers to them as "**bookmarks**"). 

Once you update to `v.1.0.2`, you can edit your settings and add a `Current Sprint Issues` bookmark with a query like `assignee = currentUser() AND sprint in openSprints()`. Make sure you *test* the config before saving to help prevent issues with the workflow. I've attached a screenshot for reference. Let me know if you run into issues!

![screen shot 2017-03-29 at 7 52 12 pm](https://cloud.githubusercontent.com/assets/4822034/24481904/a18555de-14bb-11e7-9f3a-f56b2723efec.png)

**Comment by itainoam** [comment]
Thanks for your work! Looks Awesome :) I hardcoded it in, but this is much easier.

**Comment by darkwinternight** [comment]
@steyep I have added this bookmark even before I saw that post. I don't think it needs to be built into the workflow as people have different requirements and the ability to add JQL queries as bookmarks is amazing!
