### ISSUE TITLE
Feature Request: Generic query bookmarks

### ISSUE THREAD

**Issue by seebi** [steyep/alfred-jira#42]
Hi @steyep - now with a working version of alfred-jira, I come directly to feature requests :)

I imagine to configure JQL queries to names in order to have fast access to my most important issues. Currently on top level there are two very specific queries bookmarked
- My tickets (some query with assignee = currentUser() )
- Watched issues (some query with watchedIssues() )

My feature request is to generalize that and allow any query bookmarks in that place.

**Comment by steyep** [comment]
Great suggestion @seebi! I will think about a good way to implement this but it definitely seems do-able.

**Comment by steyep** [comment]
@seebi, I've pushed up the feature branch for this request. Perhaps you can check it out and let me know what you think? You can edit the default `My Tickets` and `Watched Issues` bookmarks and add more via the settings UI:
![screen shot 2017-03-13 at 6 06 08 pm](https://cloud.githubusercontent.com/assets/4822034/23877318/1f0418f2-0818-11e7-9e89-c248aaadcd6e.png)
I think before I merge it with `master` I will allow users to upload thumbnails for the bookmarks to easily differentiate between a long list.

**Comment by seebi** [comment]
First of all - awesome response time! 👍 here my (way too long, sorry for that) review:

- Regarding the functionality:
    - Unfortunately I get constantly `400: Bad Request` errors with my query for bookmark-2, even if I copy the working queries from bookmark 0 and 1. I first thought that I need to escape the query somehow (because the of "issueKey+IN+watchedIssues()") but even this copied query did not work). I am not sure how to further debug here, since the output is not very chatty.
        - Do you change the query some before sending?
        - Do the `Sorting`, `Enabled Projects` and `Enabled Issue Statuses` config interfere with the query somehow?
        - Do you send via `GET` or `POST`?
        - In case it matters, here my test query: `status in (Done, Resolved, Closed, Rejected) ORDER BY updatedDate` name `latest closed issues`

```
2017-03-14 05:36:52][input.scriptfilter] <?xml version="1.0"?>
<items>
  <item valid="no">
    <title>400: Bad Request</title>
  </item>
</items>
```

-  Regarding the config UI:
    - UX: For the first time, it was confusing for me, where my bookmark list is after I clicked an edit button. I closed the whole screen and hoped that I did not break anything ... I think, in order to make bookmarking feature more clean, as an editor I would suggest that the list is constantly visible when I click edit and only the fields change. Doing so, I can click edit on the first bookmark, then the next, and do not change anything (but can copy/paste). But this is definitely nice to have and only a first impression (and I am not a UX pro). Also, you need to change button labels from "ADD" and "SAVE" then.
    - Small check: The "ADD" button functionality should not add empty bookmarks, if no content was added in `Name` or `Query`. The hover pointer correctly shows a stop sign but if I click anyway, it just saves an empty bookmark.

- Regarding Bookmark Icons:
    - For me its not necessary to change icons at all but,
    - rather than allowing to upload images, choosing the image from an icon library imho better since all images belong to one style then.

**Comment by steyep** [comment]
Great feedback! Exactly what I was looking for – thank you!

> Unfortunately I get constantly 400: Bad Request errors with my query for bookmark-2, even if I copy the working queries from bookmark 0 and 1.

I'm not sure I understand how that could be possible. You're saying the query works for `bookmark-0` but if you copy it as `bookmark-2` it no longer works? I've tested that and it works as intended for me. Is it possible that after making the change you forgot the click "save" in the settings, or left the settings window open? Query revisions aren't available to the Alfred workflow until the save has occurred and the `config.json` file has been re-written.
 

> Do you change the query some before sending? Do the Sorting, Enabled Projects and Enabled Issue Statuses config interfere with the query somehow?

Well, yes and no. I'm not really changing the queries by escaping characters or anything like that but I am limiting the query to the enabled projects and enabled issues statuses **unless** they are specified in the query string. So, since the query you defined contains `status`, I'm not appending the enabled statuses. But since it doesn't include `project`, I'm appending the list of enabled projects. Perhaps I should add additional configuration to each bookmark that "limits search to enabled projects?"

> Do you send via GET or POST?

Currently sending via `GET` but am considering `POST`. Do you have thoughts on why I should use one over the other?

> In case it matters, here my test query: status in (Done, Resolved, Closed, Rejected) ORDER BY updatedDate name latest closed issues

I've added your query to my bookmarks and can confirm that I'm getting the same results. Based on what I said above, does the following change resolve:
```
status in (Done, Resolved, Closed, Rejected) and project is not empty ORDER BY updatedDate
```

> UX: For the first time, it was confusing for me, where my bookmark list is after I clicked an edit button. I closed the whole screen and hoped that I did not break anything ... I think, in order to make bookmarking feature more clean, as an editor I would suggest that the list is constantly visible when I click edit and only the fields change. Doing so, I can click edit on the first bookmark, then the next, and do not change anything (but can copy/paste).

Understood and agreed. I will tweak that.

> Also, you need to change button labels from "ADD" and "SAVE" then.

Can you elaborate on that? I'm not sure that I want to have a button called "SAVE" because I think that would imply that the changes are available to the workflow – which is not the case. No changes made in the settings are available to the workflow until the settings window is closed.

> Small check: The "ADD" button functionality should not add empty bookmarks, if no content was added in Name or Query. The hover pointer correctly shows a stop sign but if I click anyway, it just saves an empty bookmark.

Nice catch. I disabled the button element but didn't disable in Angular 😔 

> For me its not necessary to change icons at all but,
> rather than allowing to upload images, choosing the image from an icon library imho better since all images belong to one style then.

I see what you're saying. But I have to think that the demographic of people that wish to change the default icon are of the same demographic that want full control over which icons they use.

**Comment by seebi** [comment]
Sorry for the late reply ... 

>> Unfortunately I get constantly 400: Bad Request errors with my query for bookmark-2, even if I copy the working queries from bookmark 0 and 1.

> I'm not sure I understand how that could be possible. You're saying the query works for bookmark-0 but if you copy it as bookmark-2 it no longer works?

yes, but this was maybe a caching error? I now changed my third query to the one you suggested and it worked (thanks). After that I tested a fourth bookmark with the first two queries and that worked too ... So I assume it was a caching issue or my operating error.

> I've tested that and it works as intended for me. Is it possible that after making the change you forgot the click "save" in the settings, or left the settings window open?

Maybe that too, yes :-(

> Query revisions aren't available to the Alfred workflow until the save has occurred and the config.json file has been re-written.

ok, understood.

> Well, yes and no. I'm not really changing the queries by escaping characters or anything like that but I am limiting the query to the enabled projects and enabled issues statuses unless they are specified in the query string. So, since the query you defined contains status, I'm not appending the enabled statuses. But since it doesn't include project, I'm appending the list of enabled projects. Perhaps I should add additional configuration to each bookmark that "limits search to enabled projects?"

ok, understood as well. And yes, at least documenting this would be fine so that one can tune it accordingly. And BTW, there are other query functions which affect project selection (e.g. [category](https://answers.atlassian.com/questions/37860559/can-i-filter-by-project-category)) so you are not able to take care of everything here and these checkboxes are important.

I've just tested your latest update and it works fine (6aaebfd).
Also the UI niceup is much more clear now.
And finally, logging the query to debug log is great, so I was able to see an error in my query :)

> > Do you send via GET or POST?
> Currently sending via GET but am considering POST. Do you have thoughts on why I should use one over the other?

GET is easier to debug in the access logs of the http server.
Beside that, no.

> > Also, you need to change button labels from "ADD" and "SAVE" then.
> Can you elaborate on that?

Sorry, I meant "ADD" and "OK" to distinguish between new and already existing bookmarks. You already make that, so forget it ...

> > For me its not necessary to change icons at all but, rather than allowing to upload images, choosing the image from an icon library imho better since all images belong to one style then.

> I see what you're saying. But I have to think that the demographic of people that wish to change the default icon are of the same demographic that want full control over which icons they use.

maybe :)
