### ISSUE TITLE
Feature Request: Go back in menu

### ISSUE THREAD

**Issue by itainoam** [steyep/alfred-jira#49]
Currently pressing backspace deletes a single char. 
After selecting a jira ticket, it makes sense that backspace will delete the whole ticket number and not just the last char.
Let me know if it doesn't makes sense. I'll try to clarify.

**Comment by steyep** [comment]
Not sure this is achievable. I *believe* that Alfred is handling all keystroke events. I think that, basically, Alfred takes your query and passes it to the script as an argument – sort of like how when you read this comment you'll be unaware of how many times I've pressed `backspace`, you'll only see what I've submitted; that's how the script sees your interaction with Alfred. 

Regardless, though, within an issue's menu you're able to filter it by typing (see example) so changing the functionality of `backspace` wouldn't work. 

![demo](https://cloud.githubusercontent.com/assets/4822034/24592125/f2d24e26-17de-11e7-8ae8-d8e7d9452e35.gif)

**Comment by steyep** [comment]
I've given this some more thought and, though I stand by my previous comment regarding how the `backspace` button works, I think adding a **Back** option to the menus would be a nice enhancement so I'm leaving this issue open and modifying the title. Thanks for the suggestion.

**Comment by ttuygun** [comment]
Hi! @steyep . There is a Alfred workflow that supports back feature that written in PHP. Here it's https://github.com/citelao/Spotify-for-Alfred

> Note: You can always leave a menu and go back just by pressing ⌫.

**Comment by steyep** [comment]
This issue has been addressed as of version `1.0.7`
