### ISSUE TITLE
HTTP 400, bad request.

### ISSUE THREAD

**Issue by danieljimenez** [steyep/alfred-jira#58]
All of my requests seem to return an HTTP 400. We have a few projects and a number of statuses, perhaps the URL is too long? It seems to be cutting off the query string based on my limited debugging

**Comment by steyep** [comment]
Please refer to issue #41 on this topic. The length of your query string shouldn't be an issue. It's more likely that one of your statuses/projects has a special character that is not being properly escaped. I'm closing this issue as a duplicate but please feel free to move the conversation over to issue #41and post any error messages you get in the debugger.

**Comment by danieljimenez** [comment]
Thanks! Sorry about that I did do a search.
