### ISSUE TITLE
Can't update ticket status

### ISSUE THREAD

**Issue by elmundio87** [steyep/alfred-jira#67]
When I try and update the status of a ticket (eg. from "Active" to "Done") the workflow fails silently.

In the debugger I get this error;

`[2017-08-10 14:51:30][ERROR: action.script] Must supply ticketId, action, and token`

**Comment by elmundio87** [comment]
Fix is in this PR https://github.com/steyep/alfred-jira/pull/68

**Comment by steyep** [comment]
@elmundio87, thanks for catching this (and the PR)! See my comments on your pull request.

Apparently, the [`atl_token`](https://community.atlassian.com/t5/Answers-Developer-Questions/quot-atl-token-quot-in-URL/qaq-p/575268) is no longer a requirement by Atlassian but I'm still requiring a value for it [here](https://github.com/steyep/alfred-jira/blob/master/lib/jira/transitions.js#L54). I will do some more research/testing and get this addressed as soon as possible. Thanks again!

**Comment by elmundio87** [comment]
No problem! I've closed the PR so you can investigate this issue independently.

For anyone else experiencing this issue, [a temporary workaround has been posted](https://github.com/steyep/alfred-jira/pull/68#discussion_r132490309).

**Comment by steyep** [comment]
This has been resolved with `v.1.0.6`.
