### ISSUE TITLE
Couldn't find a way to make it work

### ISSUE THREAD

**Issue by agzam** [steyep/alfred-jira#69]
Documentation I think misses the step - I couldn't find a way to login/authenticate, set our jira hostname, etc. *using Alfred 3.4.1*

**Comment by elmundio87** [comment]
1. In Alfred type "jira"
2. Select "Settings"
3. Select "Edit Settings"

**Comment by agzam** [comment]
![alfred-jira](https://user-images.githubusercontent.com/1091022/29433523-5faebf08-8354-11e7-9dd8-c8ba94483310.gif)
 
That's what's happening on my machine

**Comment by agzam** [comment]
I tried debugging the workflow, that's what I'm seeing:

`[2017-08-17 14:04:33][ERROR: input.scriptfilter] Code 127: /bin/bash: /usr/local/bin/node: No such file or directory`

I am using node installed through nvm. I guess should symlink binary to that

**Comment by agzam** [comment]
I have fixed the issue with not finding node, now I cannot pass Login 

```
[2017-08-17 14:11:00][STDERR: input.scriptfilter] Unable to get options. auth.checkConfig did not pass.
[2017-08-17 14:11:08][ERROR: action.script] /usr/local/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/usr/local/bin/bash: -c: line 1: syntax error: unexpected end of file
(node:22280) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Command failed: /usr/local/bin/bash -c "eval $(/usr/libexec/path_helper | awk '{print $1}') launchctl list | grep com.alfred-jira.helper | awk '{ print \$2 }'"
/usr/local/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/usr/local/bin/bash: -c: line 1: syntax error: unexpected end of file

(node:22280) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by steyep** [comment]
Hey, @agzam, I'm sorry you're having difficulties with the workflow! I mentioned in a previous issue (https://github.com/steyep/alfred-jira/issues/50) that I have no plans of supporting `nvm` but perhaps the patch posted there would help resolve your issue.

> I have fixed the issue with not finding node

Could you elaborate on what you did to fix the issue? Did you symlink to `/usr/local/bin/node` like you suggested or did you go a different route?

I unlinked my Homebrew installed version of `node`, installed it via `nvm` (v0.33.2 – probably irrelevant though), created a symlink and was able to login to the workflow without issue. These are the steps I took:
```
cd alfred-jira/
nvm install 6.0.0
nvm use 6.0.0
npm run build
ln -s $(which node) /usr/local/bin/node
```
Based on the path of your `$SHELL` environment variable, I'm assuming you're running a different version of `bash` than what is installed at `/bin/bash`? What version? I installed version `4.4.12` thinking that might be the culprit but was still able to login. So, if there's any other information that you could provide about your environment that I could re-create, I'd be happy to try and help you troubleshoot a bit more.

**Comment by agzam** [comment]
I really appreciate your effort to reproduce it. I am not being sarcastic - genuinely pleased to see that you do care about the software you've created and put out for public use. To be honest my OSD kicked-in and made me extremely anxious. I've tried all sorts of things:

 - I've symlinked nvm version of node to /usr/local/bin/node
 - I've changed NODE_PATH var
 - I've installed different versions of node
 - I've switched from `master` to `develop` and tried running `npm run build` there
 - I've rebooted my computer multiple times
 - I've got rid of nvm completely and installed node through `brew`
 - And still, the only thing I see when I type `jira` is `Login` option and it still doesn't work

**Comment by steyep** [comment]
Haha oh wow. Okay, here's a few things you can try (from the `alfred-jira` directory):
```
node -e "require('./lib/jira/keychain').delete();"
test -d ~/.alfred-jira && rm -rf ~/.alfred-jira
cd ..
rm -rf alfred-jira
git clone git@github.com:steyep/alfred-jira.git ./alfred-jira && cd $_
npm run build
npm update
```
If you're still unable to log in:
```
cat > ~/.alfred-jira/env <<-EOF
node="$(which node)"
npm="$(which npm)"
EOF
sed -i'bak' -E "s_const PATH.*_const PATH = 'source ' + require('./jira/config').cfgPath + 'env;';_" lib/alfred-exec.js
```
If that _still_ doesn't work, you can try to manually login:
```
sed -i'bak' -E "43,43d" app/main.js
npm run electron login
```
Hopefully one of those options will work for you. Let me know!

**Comment by steyep** [comment]
@agzam, were you ever able to get this working?

**Comment by agzam** [comment]
@steyep sorry, I've been swamped lately, haven't had time to play with it again.. I will definitely try it again. I really want to get this to work on my machine

**Comment by steyep** [comment]
No worries. Just following up.

**Comment by eriknomitch** [comment]
I got around this issue when using nvm by editing the workflow itself (right click on the "Script Filter") to this:

```Shell
source $HOME/.nvm/nvm.sh
node ./lib/scriptfilter.js "{query}"
```

Now the workflow will quickly source `nvm` and `node` will be set to the proper version. Your `$NODE_DIR` may differ.

![image](https://user-images.githubusercontent.com/477776/35584050-667b8a68-05b9-11e8-8aca-3c383f8fc66b.png)

**Comment by Lamadros** [comment]
holly cow finally  it's works.
Thanks @eriknomitch  for instruction. 

I only want to add this:
for determine $NODE_DIR just use this command `which node`

Also pay attention that you should change Script Filter AND Run Script ( in preference Alfred)

**Comment by ryparker** [comment]
> I got around this issue when using nvm by editing the workflow itself.
> 
> _Script Filter_
> 
> ```shell
> source $HOME/.nvm/nvm.sh
> node ./lib/scriptfilter.js "{query}"
> ```
> 
> _Run Script_
> 
> ```shell
> source $HOME/.nvm/nvm.sh
> node ./lib/action.js {query}
> ```
> 
> Now the workflow will quickly source `nvm` and `node` will be set to the proper version. Your `$NODE_DIR` may differ.
> 
> ![image](https://user-images.githubusercontent.com/477776/35584050-667b8a68-05b9-11e8-8aca-3c383f8fc66b.png)

That worked for me in Alfred 4! Thanks you!

@steyep This may be a helpful config detail to add to the README. I can open a PR if needed.

**Comment by steyep** [comment]
This workflow does not support `nvm` so adding this workaround to the README might be contradictory. That being said, I am happy this workaround works for you and that it is documented in this issue for posterity!
