### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by memelet** [steyep/alfred-jira#70]
I always get a 401 on login. Are there any logs that I can have look at?

**Comment by memelet** [comment]
Here's what alfred shows in debug mode
```
Starting debug for 'jira'

[2017-08-23 13:53:35][STDERR: input.scriptfilter] Unable to get options. auth.checkConfig did not pass.
[2017-08-23 13:54:01][ERROR: action.script] Credentials erased!
```

The first message is shown just before the login dialog is displayed.

**Comment by steyep** [comment]
A `401` error is due to invalid credentials. Does your Jira instance use a google login? You might find this link helpful:
https://community.atlassian.com/t5/JIRA-questions/JIRA-Rest-API-authentication-always-returns-401-unauthorized/qaq-p/187181

**Comment by AAlakkad** [comment]
@memelet  Did you managed to solve the issue?

**Comment by memelet** [comment]
I am using local creds. And no, I did not resolve this issue.
