### ISSUE TITLE
Login is broken

### ISSUE THREAD

**Issue by grimborg** [steyep/alfred-jira#74]
When I try to login, I get this:
```
JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Now using node v6.11.3 (npm v3.10.10)
<?xml version="1.0"?>
<items>
  <item valid="yes" arg="login">
    <title>Login</title>
    <icon>./resources/icons/login.png</icon>
  </item>
</items>
```

I got the login window once, but there's no way to get it again.

I'm using nvm, so I added this to both workflow steps that needed it:

```
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm use 6
```

**Comment by steyep** [comment]
I do not support `nvm` nor do I have plans to support it in the future. 

That being said, it looks like `nvm use 6` is writing to `stdout` which prevents Alfred from parsing the XML. You could probably resolve the issue by redirecting the output of that command:
```
nvm use 6 &> /dev/null
```

**Comment by grimborg** [comment]
That was the problem, thanks!
