### ISSUE TITLE
jira Login lot launching

### ISSUE THREAD

**Issue by leonkatz** [steyep/alfred-jira#86]
I did the setup as stated with alfred-jira, and powerpack. The workflow is installed. But when I type jira in Alfred it shows "LOGIN". When I click it nothing happens.

**Comment by steyep** [comment]
Are there any errors logged if you open Alfred's debugger?

**Comment by leonkatz** [comment]
Starting debug for 'jira'

[2017-11-03 13:40:26][STDERR: input.scriptfilter] Unable to get options. auth.checkConfig did not pass.
[2017-11-03 13:40:27][ERROR: action.script] /bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 1: syntax error: unexpected end of file
(node:12155) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Command failed: /bin/bash -c "eval $(/usr/libexec/path_helper | awk '{print $1}') launchctl list | grep com.alfred-jira.helper | awk '{ print \$2 }'"
/bin/bash: -c: line 0: unexpected EOF while looking for matching `"'
/bin/bash: -c: line 1: syntax error: unexpected end of file

(node:12155) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by leonkatz** [comment]
Just FYI I'm running High Sierra

**Comment by leonkatz** [comment]
$ /usr/libexec/path_helper
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS"; export PATH;
$ /usr/libexec/path_helper | awk '{print $1}'
PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware

Looks like space in the path might be causing the issue.

**Comment by steyep** [comment]
Ahh yeah I bet you're exactly right. Could you try applying this patch and letting me know if it resolves your issue?
```
--- a/lib/alfred-exec.js
+++ b/lib/alfred-exec.js
@@ -2,7 +2,7 @@ const child = require('child_process');
 let shell = process.env.SHELL;
 let escChr = str => str.replace(/(["\$])/g, '\\$1');
 let escSpace = str => str.replace(/ /g, '\\ ');
-const PATH = `eval $(/usr/libexec/path_helper | awk '{print $1}')`;
+const PATH = `eval $(/usr/libexec/path_helper | awk -F';' '{ print $1 }');`;
```

**Comment by leonkatz** [comment]
Updated file, now getting this error.


[2017-11-06 09:16:54][STDERR: input.scriptfilter] Unable to get options. auth.checkConfig did not pass.
[2017-11-06 09:16:55][ERROR: action.script] /bin/bash: Fusion.app/Contents/Public:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS: No such file or directory
/Users/leon.katz/work/git_sandbox/alfred-jira/lib/jira/auth.js:19
      if (err) throw err;
               ^

Error: Command failed: /bin/bash -c "eval $(/usr/libexec/path_helper | awk -F';' '{ print $1 }') npm run electron login"
/bin/bash: Fusion.app/Contents/Public:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Wireshark.app/Contents/MacOS: No such file or directory

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)

**Comment by leonkatz** [comment]
I installed electron manually, but still got the same error. Was able to run the command from the command line and get the login screen.

**Comment by steyep** [comment]
@leonkatz can you let me know if this works?:
```
--- a/lib/alfred-exec.js
+++ b/lib/alfred-exec.js
@@ -2,16 +2,16 @@ const child = require('child_process');
 let shell = process.env.SHELL;
 let escChr = str => str.replace(/(["\$])/g, '\\$1');
 let escSpace = str => str.replace(/ /g, '\\ ');
-const PATH = `eval $(/usr/libexec/path_helper | awk '{print $1}')`;
+const PATH = `eval $(echo "$(/usr/libexec/path_helper -s)" | awk -F';' '{ print $1 }');`;

 module.exports = {
   'exec': (cmd, options, callback) => {
-    cmd = escChr(cmd);
-    return child.exec(`${shell} -c "${PATH} ${cmd}"`, options, callback);
+    cmd = escChr(`${PATH} ${cmd}`);
+    return child.exec(`${shell} -c "${cmd}"`, options, callback);
   },
   'execSync': (cmd, options) => {
-    cmd = escChr(cmd);
-    return child.execSync(`${shell} -c "${PATH} ${cmd}"`, options);
+    cmd = escChr(`${PATH} ${cmd}`);
+    return child.execSync(`${shell} -c "${cmd}"`, options);
```

**Comment by leonkatz** [comment]
This worked great. Thank you for the quick response.

**Comment by steyep** [comment]
Great! I'll get this merged into `master` then. Thanks for testing!
