### ISSUE TITLE
In Settings "Unable to Check for Updates. No Git Repo Found"

### ISSUE THREAD

**Issue by ryanmumby** [steyep/alfred-jira#96]
As you can see in the attached screenshot, I can't access any options within **Settings**

<img width="557" alt="screen shot 2018-04-09 at 2 43 18 pm" src="https://user-images.githubusercontent.com/24573618/38516691-d2d4085c-3c05-11e8-8025-80491f841ec3.png">

Logging gives me the following

```
[2018-04-09 14:52:59][STDERR: input.scriptfilter] fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
```

I can access settings manually using  
`npm -s run electron`

Tried to delete node_modules and rerun the build as mentioned in #89 but it didn't resolve.

**Comment by steyep** [comment]
Did you clone the repo or just download it? It's throwing that error because it can't find the `.git` directory.

**Comment by ryanmumby** [comment]
@steyep  i think i may have downloaded - is there a way to quickly correct this or do I have to clone and start from scratch?

**Comment by steyep** [comment]
I believe you'll need to remove the existing workflow, clone this repo, and reinstall it. The good news, however, is that all of your settings/configurations are saved in a separate directory (`~/.alfred-jira`) so your settings shouldn't be affected.

That being said, it's still probably a good idea to make a copy of that directory before moving things around.

**Comment by ryanmumby** [comment]
This worked! Thanks.
